# Generated by Django 3.1.3 on 2021-02-17 21:50

from django.db import migrations, models
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_update_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectpermission',
            name='actions',
            field=utilities.fields.JSONArrayField(base_field=models.CharField(max_length=30)),
        ),
        migrations.AddField(
            model_name='objectpermission',
            name='actions',
            field=utilities.fields.JSONArrayField(
                base_field=models.CharField(max_length=30)
            ),
        ),
    ]
