# Generated by Django 3.1.7 on 2021-02-24 23:00

from django.db import migrations, models
import nautobot.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_initial_part_4'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rackreservation',
        #     name='units',
        # ),
        migrations.AddField(
            model_name='rackreservation',
            name='units',
            field=nautobot.utilities.fields.JSONArrayField(base_field=models.PositiveSmallIntegerField()),
        ),
    ]
