# Generated by Django 3.1.7 on 2021-02-24 23:16

from django.db import migrations, models
import nautobot.dcim.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_auto_20210224_2300'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='cablepath',
        #     name='path',
        # ),
        migrations.AddField(
            model_name='cablepath',
            name='path',
            field=nautobot.dcim.fields.JSONPathField(base_field=models.CharField(max_length=40)),
        ),
    ]
