# Generated by Django 3.1.7 on 2021-02-24 23:16

from django.db import migrations, models
import nautobot.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='objectpermission',
        #     name='actions',
        #     field=nautobot.utilities.fields.JSONArrayField(base_field=models.CharField(max_length=30)),
        # ),
        migrations.AddField(
            model_name='objectpermission',
            name='actions',
            field=nautobot.utilities.fields.JSONArrayField(base_field=models.CharField(max_length=30)),
        ),
    ]
