# Generated by Django 3.1.7 on 2021-02-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_auto_20210224_2058'),
        ('ipam', '0003_auto_20210224_2316'),
    ]

    operations = [
    ]
