# Generated by Django 3.1.3 on 2021-02-17 21:50

from django.db import migrations, models
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0060_customlink_url_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='choices',
        ),
        migrations.AddField(
            model_name='customfield',
            name='choices',
            field=utilities.fields.JSONArrayField(base_field=models.CharField(max_length=100), blank=True, null=True),
        ),
    ]
