# Generated by Django 3.1.7 on 2021-02-24 23:16

from django.db import migrations, models
import nautobot.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_populate_default_status_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='choices',
        ),
        migrations.AddField(
            model_name='customfield',
            name='choices',
            field=nautobot.utilities.fields.JSONArrayField(base_field=models.CharField(max_length=100), blank=True, null=True),
        ),
    ]
